### ISSUE TITLE
Inconsistent flag values

### ISSUE THREAD

**Issue by emurmotol** [rollout/rox-go#52]
We're initializing rollout like so:

```
// domain/flags.go

package domain

import (
	"github.com/rollout/rox-go/v5/server"
)

var (
	Flags = &RolloutFlags{
		EnablePostManualTableRatings: server.NewRoxFlag(false),
	}
)

type RolloutFlags struct {
	EnablePostManualTableRatings server.RoxFlag
}

```

```
// rollout.go

import (
	"github.com/rollout/rox-go/v5/server"
	"solaireresort.com/playerrating/config"
	"solaireresort.com/playerrating/handler"
)

func rolloutInit() {
	newRox := server.NewRox()
	newRox.Register("playerratings.playerrating.domain.Flags", domain.Flags)
	<-newRox.Setup(config.RolloutEnvironmentKey, nil)
	handler.Rox = newRox
}
```

And the time we check the flag

```
// handler/handler.go

...

Rox.SetCustomStringProperty("playerratings.playerrating.proto.playerrating.Enriched.TableId", e.TableId)
if domain.Flags.EnablePostManualTableRatings.IsEnabled(nil) {
        // fire!!
}

...

```

It works but, sometimes returned flag values are not accurate. Example,

![image](https://user-images.githubusercontent.com/14858825/179929536-a6ab4d18-c44b-464e-9dbe-014cb80b3c72.png)

Since these values (masked in red) are listed in this flag, it should always return true. 

But, when we try to remove an item from the list of values.

**Still, the flag returns true. This happens intermittent, sometimes it works.**

Need your assistance to understand the issue.

Thank you!

**Comment by tfennelly** [comment]
Hey @emurmotol.

So just to be clear, are you saying that you your client app (golang app using the SDK) is not always getting flag audience config changes in a timely manner? You make some audience config changes on the flag and the SDK continues to evaluate the flag according to the old audience config ?

**Comment by tfennelly** [comment]
Sounds like you resolved the issue and there's some missing docs. Maybe we can get some info and make sure the documentation gets fixed.

Thanks @emurmotol and sorry for the inconvenience !!

**Comment by emurmotol** [comment]
I tried this,

```
rolloutOptions := server.NewRoxOptions(server.RoxOptionsBuilder{
      FetchInterval: 1 * time.Second,
})
```

But, the issue persist.

**Comment by emurmotol** [comment]
> Hey @emurmotol.
> 
> So just to be clear, are you saying that you your client app (golang app using the SDK) is not always getting flag audience config changes in a timely manner? You make some audience config changes on the flag and the SDK continues to evaluate the flag according to the old audience config ?

that is correct

**Comment by emurmotol** [comment]
> Sounds like you resolved the issue and there's some missing docs. Maybe we can get some info and make sure the documentation gets fixed.
> 
> Thanks @emurmotol and sorry for the inconvenience !!

I tried this,

rolloutOptions := server.NewRoxOptions(server.RoxOptionsBuilder{
      FetchInterval: 1 * time.Second,
})
But, the issue persist.

**Comment by AsafRollout** [comment]
there was a bug with the fetch interval that got resolved
but push notification should have initiated a fetch regardless

anyway, i'm closing it for now, as it's been 7 months ago
please open a new ticket if the problem persist
